version: '3.8'

services:
  app:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - db
    env_file:
      - app/.env

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: products_db
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:

